permalink: /:categories/:year-:month-:day-:title/
google_analytics_id: UA-707544-6
url: ''
prose:
  metadata:
    "journal/_posts": |
      title: 
      layout: post
    "writing/_posts": |
      title:
      layout: post