permalink: /:categories/:year-:month-:day-:title/
google_analytics_id: UA-707544-6
url: 'https://www.matthewgatland.com'
title: Matthew Gatland
description: Matthew Gatland's personal website
markdown: kramdown
future: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: null
prose:
  metadata:
    "journal/_posts": |
      title: 
      layout: normal.html
